rest/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register')
]

rest/home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home')
]

rest/rest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

rest/accounts/models.py
from django.db import models

# Create your models here.

rest/home/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=30)
    age = models.PositiveSmallIntegerField()
    email = models.EmailField()

    def __str__(self):
        return self.name

rest/accounts/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from django.contrib.auth.models import User
from .serializers import UserRegisterSerializer


class RegisterView(APIView):
    def post(self, request):
        ser_data = UserRegisterSerializer(data=request.POST)
        if ser_data.is_valid():
            User.objects.create_user(
                username=ser_data.validated_data['username'],
                email=ser_data.validated_data['email'],
                password=ser_data.validated_data['password']
            )
            return Response(ser_data.data)
        return Response(ser_data.errors)


rest/home/views.py
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import Person
from .serializers import PersonSerializer


# @api_view(['GET', 'POST', 'PUT'])
# def home(request):
#     return Response({'name': 'ali'})


class Home(APIView):
    def get(self, request):
        persons = Person.objects.all()
        ser_data = PersonSerializer(instance=persons, many=True)
        return Response(data=ser_data.data)




rest/home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}
    <h3>Home page</h3>
{% endblock %}

rest/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Title</title>
    <style>
        .jombotron{
             padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
    </style>
</head>
<body>
    {% include 'inc/nav.html' %}
    <div class="jombotron">
        {% include 'inc/messages.html' %}

        {% block content %} {% endblock %}
    </div>
</body>
</html>

rest/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
       <p class="alert alert-{{ msg.tags }}"> {{ msg }} </p>
    {% endfor %}
{% endif %}

rest/templates/inc/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'home:home' %}">Home</a>
      </div>
    </div>
  </nav>